defaults: &defaults
  working_directory: /home/adios2
  steps:
    - checkout:
        path: /home/adios2/source
    - run:
        name: Update
        command: bash source/scripts/ci/runOnCircle.sh update
    - run:
        name: Configure
        command: bash source/scripts/ci/runOnCircle.sh configure
    - run:
        name: Build
        command: bash source/scripts/ci/runOnCircle.sh build
    - run:
        name: Test
        command: |
          ulimit -c unlimited
          bash source/scripts/ci/runOnCircle.sh test
    - run:
        command: |
          mkdir -p /tmp/core_dumps
          find . -name '*core*' | xargs bash -c 'for F in $@; do if file -b "$F" | grep -q "core file"; then cp -v --parents "$F" /tmp/core_dumps; fi; done'
        when: on_fail
    - store_artifacts:
        path: /tmp/core_dumps

version: 2

jobs:
  "fedora-ubsan":
    <<: *defaults
    docker:
      - image: ornladios/adios2-auto:fedora-ubsan

  "fedora-openmpi-ubsan":
    <<: *defaults
    docker:
      - image: ornladios/adios2-auto:fedora-openmpi-ubsan

workflows:
  version: 2
  build:
    jobs:
      - "fedora-ubsan"
      - "fedora-openmpi-ubsan"
