name: adios2-python-docs

channels:
  - conda-forge
  - williamfgc

dependencies:
  - python
  - adios2-openmpi
  - pip:
    - sphinx
    - blockdiag>=1.5.4
    - sphinxcontrib-blockdiag>=1.5.5
    - sphinx_rtd_theme>=0.4.1
    - breathe==4.14.1
